"""tabela de associação Consultas criada, __tablename__ adicionado

Revision ID: 0afb2788c532
Revises: 71abe0e60966
Create Date: 2024-07-18 22:45:18.193967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afb2788c532'
down_revision = '71abe0e60966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medic_id', sa.Integer(), nullable=False),
    sa.Column('consult_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medic_id'], ['medic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultations')
    # ### end Alembic commands ###
