"""notas não é required

Revision ID: 0d389f8e81d9
Revises: 508d5327082a
Create Date: 2024-07-30 19:15:00.677683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d389f8e81d9'
down_revision = '508d5327082a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'medic', ['medic_id'], ['id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
