"""Lenght of patient cpf column

Revision ID: 567df9519730
Revises: c5b69435e32d
Create Date: 2025-03-31 12:33:29.699420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567df9519730'
down_revision = 'c5b69435e32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
