"""column role set to array of strings

Revision ID: 599ed8b159df
Revises: c524848a6b6c
Create Date: 2025-02-11 18:10:17.674500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599ed8b159df'
down_revision = 'c524848a6b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'medic', ['medic_id'], ['id'])

    with op.batch_alter_table('medic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.JSON(), server_default='["medic"]', nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.JSON(), server_default='["patient"]', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('medic', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
