"""tabela medic criada

Revision ID: 71abe0e60966
Revises: 7f6f3157b5b8
Create Date: 2024-07-17 12:27:08.338607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71abe0e60966'
down_revision = '7f6f3157b5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('specialty', sa.String(length=40), nullable=False),
    sa.Column('crm', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medic')
    # ### end Alembic commands ###
