"""aumento do campo hash do patient tambem

Revision ID: 73bc2e50c987
Revises: 74d58d34d72d
Create Date: 2024-10-09 19:29:09.908740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73bc2e50c987'
down_revision = '74d58d34d72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'medic', ['medic_id'], ['id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
