"""Add role column for Patient and Medic

Revision ID: c524848a6b6c
Revises: 73bc2e50c987
Create Date: 2025-01-27 20:05:22.037757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c524848a6b6c'
down_revision = '73bc2e50c987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'medic', ['medic_id'], ['id'])

    with op.batch_alter_table('medic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('medic', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
