"""Role column of patient set to array of text

Revision ID: c5b69435e32d
Revises: ee0268e1e08f
Create Date: 2025-03-31 12:19:59.507749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5b69435e32d'
down_revision = 'ee0268e1e08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{''patient''}'::character varying[]"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True,
               existing_server_default=sa.text("'{''patient''}'::character varying[]"))

    # ### end Alembic commands ###
