"""data e hora da consulta unida em uma só

Revision ID: d51624a51b00
Revises: 0d389f8e81d9
Create Date: 2024-07-31 12:52:27.454726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd51624a51b00'
down_revision = '0d389f8e81d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'medic', ['medic_id'], ['id'])
        batch_op.drop_column('consult_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consult_date', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
