"""Column cpf added to patient

Revision ID: ee0268e1e08f
Revises: 4f227f1e8818
Create Date: 2025-03-31 12:14:21.997610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee0268e1e08f'
down_revision = '4f227f1e8818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medic', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{''medic''}'::character varying[]"))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cpf')

    with op.batch_alter_table('medic', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True,
               existing_server_default=sa.text("'{''medic''}'::character varying[]"))

    # ### end Alembic commands ###
